### ISSUE TITLE
Check Podman works on desktops and laptops

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#100]
Check we can deploy Podman on our desktops and laptops.

- Verify that Podman works as expected and is compatible with our deployments.

**Comment by Zarquan** [comment]
My desktop and laptop are both running Fedora 31.

Podman runs fine, although need to add the `z` option to volume mounts to grant the appropriate SELinux permissions to the containers.

**Comment by Zarquan** [comment]
@stvoutsin Can you check to see if Podman runs OK on your machines.

**Comment by stvoutsin** [comment]
> @stvoutsin Can you check to see if Podman runs OK on your machines.

@Zarquan I've installed Podman on my local machine (Ubuntu 18.04) with the following instructions:

```
echo 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_Unstable/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_Unstable/Release.key | sudo apt-key add -
# Debian Testing
echo 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_Testing/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_Testing/Release.key | sudo apt-key add -
# Debian 10
echo 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_10/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_10/Release.key | sudo apt-key add -

sudo apt-get update -qq
sudo apt-get -qq -y install podman
```

I then tried running the openstack client container as: 
```
podman run \
         --rm \
         --tty \
         --interactive \
         --hostname openstacker \
         --volume "${HOME}/clouds.yaml:/root/clouds.yaml" \
         atolmis/openstack-client \
         bash
```

This seems to work as the container gets fetched and I am taken to the root@openstacker prompt, although I do see the following error:

> ERRO[0080] could not find slirp4netns, the network namespace won't be configured: exec: "slirp4netns": executable file not found in $PATH

**Comment by Zarquan** [comment]
Did you get the instructions from the Podman site ?
https://podman.io/getting-started/installation.html

**Comment by stvoutsin** [comment]
> Did you get the instructions from the Podman site ?
> https://podman.io/getting-started/installation.html

Yep, that's what I used to install

**Comment by Zarquan** [comment]
Quick check on Google finds this
https://github.com/rootless-containers/slirp4netns

Debian/Ubuntu install
https://github.com/rootless-containers/slirp4netns#debian-gnulinux-10-or-later--ubuntu-1904-or-later

    sudo apt install slirp4netns

**Comment by Zarquan** [comment]
Additional information
https://github.com/containers/libpod/issues/1234

**Comment by stvoutsin** [comment]
`sudo apt install slirp4netns
`
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 slirp4netns : Depends: libslirp0 (>= 4.1.0-1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

`sudo apt install libslirp0
`
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libslirp0 : Depends: libc6 (>= 2.28) but 2.27-3ubuntu1 is to be installed
             Depends: libglib2.0-0 (>= 2.57.2) but 2.56.4-0ubuntu0.18.04.6 is to be installed
E: Unable to correct problems, you have held broken packages.

`sudo apt install libc6
`
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libc6 is already the newest version (2.27-3ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.

**Comment by stvoutsin** [comment]
Will look into this more tomorrow

**Comment by Zarquan** [comment]
No problem, not urgent. Just all the examples I'm creating use podman rather than docker, so need to check I'm not breaking anything.

**Comment by Zarquan** [comment]
I expect there may be a few issues with compose, and almost certainly issues with swarm.

**Comment by Zarquan** [comment]
@stvoutsin  Could you run another test to see if Ubuntu have updated their packages ?

**Comment by Zarquan** [comment]
This is no longer an issue.
Everything we use is using Podman and Buildah.
