### ISSUE TITLE
Evaluate use of PySpark MLib and other options for Machine Learning via Spark

### ISSUE THREAD

**Issue by stvoutsin** [wfau/aglais#102]
Spark provides out of the box Machine learning algorithms, including for clustering via MLib
https://spark.apache.org/docs/latest/mllib-clustering.html

Evaluate how they could potential be used in our system, or alternative options for running ML tasks on the Gaia data.

**Comment by Zarquan** [comment]
Needs detailed notes and examples for things that work, and things that don't. With sufficient detail to work as a learning resource for others.

**Comment by Zarquan** [comment]
This is an open ended task with no real endpoint.
We can replace it with specific tasks for specific ML tools or algorithms if we need to.
