### ISSUE TITLE
Fine tune Spark/Yarn configuration

### ISSUE THREAD

**Issue by stvoutsin** [wfau/aglais#103]
We need to fine tune the Spark/Yarn configuration. This requires us to figure out answers to:

- How many executors?
- How much memory/cores per executor
- What about the Yarn nodemanager? How much memory (min/max allocations)
- Is there a single set of values for the most efficient resource allocation?
- How does Spark handle partitions, jobs, tasks, shuffling ? 
- ... and much more

**Comment by Zarquan** [comment]
Yep - We also need automated tests to check each of these.

**Comment by Zarquan** [comment]
Is this different to #95 and #96 ?

**Comment by stvoutsin** [comment]
Possibly related, and can be merged, but I interpreted those as defining/documenting what values need to be modified, where, and what effects they may have, where this task is to actually try to understand what the correct values need to be for each configuration parameter.

**Comment by Zarquan** [comment]
As long as we end up with a list that documents "we need to set param [xxx] to value [yyy] because [zzzz]" and "run test [www] to check that param [xxx] is set correctly" then is fine.

**Comment by stvoutsin** [comment]
Some useful information related to this issue that I've found is documented here:
https://github.com/stvoutsin/aglais/blob/13404bae190577926b2ad0f36085d54d29393d29/notes/stv/20200429-spark-fine-tuning.txt

I've also documented some Spark usage examples here, in the process of trying to understand the best ways of using pySpark:
https://github.com/stvoutsin/aglais/blob/13404bae190577926b2ad0f36085d54d29393d29/notes/stv/20200429-spark-tips.txt

**Comment by Zarquan** [comment]
Will the 'optimal' settings depend on the type of analysis you are running ?
If so, then in order to be able to document what settings are best for what tasks, this task depends on things like 
1. library of example analysis tasts #24 
2. template form for benchmarks #41
3. list of curated notebooks #84
