### ISSUE TITLE
Curated list of 3rd party Python libraries

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#104]
This needs to include details of what they are used for, which version(s) we need and links to documentation etc. Also needs test scripts and/or notebooks that can verify the libraries are installed and working correctly.

Example from #67 
- HDBSCAN installed for the “Kounkel and Covey groups demo” notebook
  - version installed on live site
  - link to documentation
  - list of dependencies
  - conflicts with other packages
  - test scripts and notebooks

**Comment by stvoutsin** [comment]
I've started documenting some of this:
    https://github.com/stvoutsin/aglais/commit/298fd8734ee880959bb810b5701b93e89726424f

Also commited a pip requirements, file produced using pip freeze > requirements.txt on a worker node:
    https://github.com/stvoutsin/aglais/commit/3fca12fe49d732b1bd674757b78fe9664704c4a4

**Comment by Zarquan** [comment]
Can we create a new updated list of the things we need.

**Comment by Zarquan** [comment]
Can we resolve this into a URL pointing at a plain text file listing the required and optional Python libraries, with version numbers, preferably merged into the main aglais code base.

**Comment by Zarquan** [comment]
Is `requirements.txt` the right format for this ?
https://note.nkmk.me/en/python-pip-install-requirements/

Being able to install everything we need using a single `pip install` command would be useful.

**Comment by Zarquan** [comment]
Does the `requirements.txt` file in `gdaf-openstack` resolve this ?
https://github.com/wfau/aglais/blob/master/experiments/stv/gdaf-openstack/config/requirements.txt

**Comment by Zarquan** [comment]
https://pip.pypa.io/en/stable/user_guide/#requirements-files
