### ISSUE TITLE
Experiment with Hadoop (Yarn/HDFS) on Kubernetes

### ISSUE THREAD

**Issue by badeWay** [wfau/aglais#105]
Deploy Hadoop and experiment with HDFS and creating Yarn jobs, on a Kubernetes cluster.
Investigate and document different configurations, and run benchmarks to compare with existing system

**Comment by Zarquan** [comment]
@stvoutsin This you ?

**Comment by stvoutsin** [comment]
@Zarquan Yep, I was swapping between a few account, testing out Github OAuth, must have not logged out from that account while creating this issue

**Comment by Zarquan** [comment]
Suggest some further investigations
1. Spark and Hadoop on a separate K8s clusters
2. Spark and Hadoop on the same K8s cluster
3. Data transfers and performance tests between Spark and Hadoop
4. What creates the mapping between Openstack volumes, K8s storage and HDFS mounts ?
5. How do we scale the number of nodes, create with 4 nodes, scale to 5, 6, 7 and 8 nodes ...
6. How do we scale the size of storage, create with 100Gi, scale to 200Gi, 250Gi ...

**Comment by Zarquan** [comment]
We don't need Yarn inside K8s, because K8s does the scheduling for us.
We might need HDFS, but that would be a separate issue.
