### ISSUE TITLE
Experiment & Document integration of AXS into our system

### ISSUE THREAD

**Issue by stvoutsin** [wfau/aglais#157]
https://axs.readthedocs.io/en/latest/installation.html
https://iopscience.iop.org/article/10.3847/1538-3881/ab2384

**Comment by Zarquan** [comment]
@stvoutsin Can you add a summary of where we are with this?

**Comment by Zarquan** [comment]
Follow on issues #221, #222, #223 ans #224.

**Comment by stvoutsin** [comment]
Some initial experiments trying to get this to work here: https://github.com/stvoutsin/aglais/blob/issue-157/notes/stv/20201211-AXS-Tests.txt
