### ISSUE TITLE
Generate Parquet schema from WFAU metadoc

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#179]

**Comment by Zarquan** [comment]
This GitHub project contains schemas for all the WFAU databases:
https://github.com/wfau/metadata/tree/master/metadocs

We have PySpark code that can convert the cvs files into Parquet files:

**Comment by NigelHambly** [comment]
Done - see https://github.com/wfau/aglais/issues/42#issuecomment-746014749
