### ISSUE TITLE
User space ssh rsync access

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#195]
Users will want to have some level of external read/write access to their user space.
Something like a tiny VM that has write access to their user space.

This is based on a use case from Nigel, uploading his own data to add to the data already in the system.

**Comment by Zarquan** [comment]
Split this into two steps
1. Short term implementation now, a VM or a Pod that Nigel can use ssh/rsync to upload data.
2. Longer term, managed solution for other users

**Comment by Zarquan** [comment]
We have notes and a working example of how to import an existing Manila/CephFS share into a plain Openstack VM. Result is we can mount a Manila/CephFS share into the Openstack VMs used for the manual deploy, and for the Ansible based deployment.

Code and notes are on my working branch at the moment, I'll transfer them onto a separate branch and create a PR just for this issue.

**Comment by Zarquan** [comment]
We have working code for publishing the Gaia DR2 data as a Ceph share and mounting it as a read only directory in the Ansible managed virtual machines. (PR #202)

Next steps are to create a Ceph share for user data and mounting it as a read/write directory.

**Comment by Zarquan** [comment]
We have working code for publishing and mounting a read/write Ceph share for Nigel to work on importing new data sets (PR #202).

**Comment by Zarquan** [comment]
Is this done now ?

**Comment by stvoutsin** [comment]
I think this is done. Closing issue
