### ISSUE TITLE
Astroquery and astropy

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#197]
Install astroquery and astropy and create example notebooks to test they work.

**Comment by Zarquan** [comment]
Parts of this are a duplicate of #181

**Comment by stvoutsin** [comment]
Astroquery has now been installed on the Live prototype service.
I created an example notebook to demonstrate that it works and ran it successfully:
https://github.com/stvoutsin/aglais/blob/stv-ansible-deploy/experiments/stv/notebooks/astroquery.json

Astroquery is also now included in the automated deployment notes that are being worked on here:
https://github.com/stvoutsin/aglais/blob/stv-ansible-deploy/experiments/stv/ansible/29-install-pip-libs.yml

**Comment by stvoutsin** [comment]
Can we classify this as done?

**Comment by Zarquan** [comment]
I get a 404 response from these URLs, have the files moved ? 

> https://github.com/stvoutsin/aglais/blob/stv-ansible-deploy/experiments/stv/notebooks/astroquery.json

> https://github.com/stvoutsin/aglais/blob/stv-ansible-deploy/experiments/stv/ansible/29-install-pip-libs.yml

Also might be better to have URLs that point to files in the wfau repository rather than your private one.

**Comment by Zarquan** [comment]
How do we make sure that these tests are run whenever we create a new deployment ?

**Comment by Zarquan** [comment]
Do the test notebooks return a result that we can extract from the REST service response and check the result ?

**Comment by Zarquan** [comment]
> Can we classify this as done?

Yep - this one is done.

I think we have some new ones that follow on from this
* Create a list of integration tests #253
*  Execute integration tests via the Zeppelin REST API #254

**Comment by Zarquan** [comment]
This one is done - testing moved to a new issue #300.
