### ISSUE TITLE
Homescreen notebook

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#204]
Interesting config property:
```
// use specified notebook (id) as homescreen
ZEPPELIN_NOTEBOOK_HOMESCREEN("zeppelin.notebook.homescreen", null),

```
Do we want to make use of this ?

**Comment by Zarquan** [comment]
What is the first thing that we want our users to see ?

The example notebooks are our main documentation, so they will be the main thing that our users interact with. Making them clear, consistent and easy to read will have a big impact on the user experience.

**Comment by NigelHambly** [comment]
The way I see it the existing home screen should be utilised and hence adjusted for this purpose. Hence we have "Welcome to Zeppelin" in big friendly letters, then below a small folder tree consisting of

- Public Examples
- Users

where the "start here" notebook has been renamed to "AAA Start here" so it appears at the top when a user naturally clicks on that to explore what's available. I'm in the process of doing all this under the auspices of #234 and #443 so in the interests of tidiness I'm closing this issue as taken care of.
