### ISSUE TITLE
Create aglais-notebooks GitHub repository

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#216]
Create a new GitHub repository : https://github.com/wfau/aglais-notebooks
This is part of #56

**Comment by stvoutsin** [comment]
Do we want to close this issue? And perhaps replace with the next phases of it, i.e. Annotate each folder/notebook with a README description?

**Comment by Zarquan** [comment]
Done - see https://github.com/wfau/aglais-notebooks
