### ISSUE TITLE
Standard copyright, licence terms and description header for the Aglais notebooks.

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#218]
Add a MarkDown cell at the top of each notebook with the licence terms.
Suggest the Creative Commons [Attribution-ShareAlike](https://creativecommons.org/licenses/by-sa/4.0/) license.

**Comment by Zarquan** [comment]
Looks like the [aglais-notebooks](https://github.com/wfau/aglais-notebooks) repository is already linked to the [GPL](https://github.com/wfau/aglais-notebooks/blob/main/LICENSE).
Confirm Nigel is happy with that, or would the [Creative Commons SA](https://creativecommons.org/licenses/by-sa/4.0/) licence be more appropriate for teaching examples.

**Comment by Zarquan** [comment]
The example notebooks are our main documentation, so they will be the main thing that our users interact with. Making them clear, consistent and easy to read will have a big impact on the user experience.

**Comment by NigelHambly** [comment]
I have included the following in the top cell of all public notebooks, commented out with html tags:

    Gaia Data Processing and Analysis Consortium (DPAC) 
    Co-ordination Unit 9 Work Package 930
    
    (c) 2005-2025 Gaia DPAC
    
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.

and I'll appended to the first line ", based on original example scripts provided by the Apache Software Foundation" where I've based examples on their tutorials.
