### ISSUE TITLE
AXS testing

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#223]
Follow on from #221 and #222, create some tests that demonstrate that AXS in installed and working.
Specifically tests that will pass/fail if AXS in working or not.

**Comment by NigelHambly** [comment]
Following checks and discussions with @Zarquan and @stvoutsin we need to carefully check the accuracy of AXS crossmatching. A couple of known (within github) bugs have been rediscovered in our tests which showed the axsdist column to be strange, and crossmatching incomplete near (at least) the North Celestial Pole. See for example

- [astronomy-commons#22]
- [astronomy-commons#23]

These are illustrated in the "AXS testing" Zeppelin notebook in the AXS deployment prototype when comparing with WFAU's independent plain-sweep implementation cross-match SW between the same two catalogues (Gaia DR2 & 2MASS).

**Comment by NigelHambly** [comment]
Decided to suspend indefinitely all AXS-related work owing to seemingly fundamental flaws in it's current implementation
