### ISSUE TITLE
Ceph shares not visible from Openstack "test" project

### ISSUE THREAD

**Issue by stvoutsin** [wfau/aglais#227]
When trying to list the shares in Openstack from the "test" project using the command line client, I get an empty response.

Shares are visible from all projects using the Openstack GUI however.
Notes on how I deployed the version that I was testing with, and the step that is failing for me are here:
https://github.com/stvoutsin/aglais/blob/stv-ansible-deploy/notes/stv/20201102-automated-deploy.txt#L803

**Comment by Zarquan** [comment]
This should be fixed in PR #228.

**Comment by Zarquan** [comment]
As far as I know this is fixed.
