### ISSUE TITLE
Spark and Hadoop versions

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#238]
Check we are using the right versions fo Spark and Hadoop in the Ansible deployment.

[20-install-spark.yml#L29](https://github.com/wfau/aglais/blob/master/experiments/hadoop-yarn/ansible/20-install-spark.yml#L29)
```
spfull: "spark-2.4.7-bin-hadoop2.7"
```
[11-install-hadoop.yml#L33](https://github.com/wfau/aglais/blob/master/experiments/hadoop-yarn/ansible/11-install-hadoop.yml#L33)
```
hdname: "hadoop-3.1.3"
```

**Comment by stvoutsin** [comment]
I don't think this is still an outstanding issue. The current versons are compatible and work, and we are planning on testing the newest versions.

**Comment by Zarquan** [comment]
> I don't think this is still an outstanding issue. 

Yes, this is still an issue.
We are installing Hadoop version 3.1.3 but the Spark binary we are using, spark-2.4.7-bin-hadoop2.7, is built for Hadoop 2.7.

> The current versons are compatible and work, 

They may appear to work - but they are not the right versions.

> and we are planning on testing the newest versions.

Can you link to the issue for that ?

https://github.com/wfau/aglais/blob/68d876560b173358f4234e5e0cda08a0f6123c4f/deployments/hadoop-yarn/ansible/config/medium-04.yml#L29
https://github.com/wfau/aglais/blob/68d876560b173358f4234e5e0cda08a0f6123c4f/deployments/hadoop-yarn/ansible/config/medium-04.yml#L44

**Comment by Zarquan** [comment]
No longer an issue.
