### ISSUE TITLE
Configuration for Ansible deployment

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#240]
Create configuration files for the Ansible deployment
* Deployment secrets
* Cluster size
   * Master and worker count
   * Memory and disc space

* Zeppelin, Spark and Hadoop versions

**Comment by Zarquan** [comment]
Possibly using `yq` to merge YAML configuration files from the main code base, user desktop/laptop and user input.

**Comment by Zarquan** [comment]
Can we pass more than one `values.yaml` file to an Ansible playbook ?

**Comment by stvoutsin** [comment]
It looks like this is already done.
