### ISSUE TITLE
Find out how public/private workspaces work

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#251]
https://zeppelin.apache.org/docs/0.7.0/security/notebook_authorization.html#separate-notebook-workspaces-public-vs-private

**Comment by Zarquan** [comment]
@stvoutsin I think you did some work on this ? Could you write up a note to describe what you found.

**Comment by stvoutsin** [comment]
Information on this available here: https://github.com/wfau/aglais/blob/master/notes/stv/20201201-notebook-visibility.txt 
Also here: https://zeppelin.apache.org/docs/0.8.0/setup/security/notebook_authorization.html

**Comment by Zarquan** [comment]
OK, so that isn't what I meant when I created this issue.

The zeppelin page on notebook authorization tells us what config setting to use, but it doesn't tell us where the notebooks are stored. How does Zeppelin handle different users taking a copy of a shared notebook and creating their own private editable version. Where are and how are the new copies stored ? Do we need to back them up ? Can we map them onto a directory in the user's home space ? 

What I also think we need is to document what public/private workspaces mean for our users. What do our users see when they access a shared notebook? If the Gaia science examples are shared, does that mean they have to be read-only to prevent users from modifying them. How easy is it for one of our users to take a copy of the read-only shared example notebook and make their own read-write copy ?

What I was after was a review of the public/private shared/owned notebooks work in terms of user experience, so that we can decide what we want to provide to our users.
Do we want to allow end users to create new shared notebooks, and if so where ? We probably want to control the top level folders, otherwise the entry point will have lots of 'test-one' 'mytest' and 'firstnb' fragments.  

I think this probably means a couple of people spending a day working together, experimenting with public and private notebooks, editing and running shared notebooks.

I'm re-opening this for now so that we don't loose track of this. First task is probably to come up with a better definition of what needs to be done, possibly splitting it into separate smaller tasks.

**Comment by Zarquan** [comment]
No longer an issue.
