### ISSUE TITLE
Zeppelin unable to commit to the notebook Github repository

### ISSUE THREAD

**Issue by stvoutsin** [wfau/aglais#266]
This error occured on the live prototype currently in use by Nigel. The deploy process and the integration with Github is described here:

Error message: 
Couldn't checkpoint note revision: possibly storage doesn't support versioning. Please check the logs for more details.

https://github.com/stvoutsin/aglais/blob/master/notes/stv/20201128-ansible-deploy-hadoop-zeppelin-02.txt

**Comment by Zarquan** [comment]
@stvoutsin Has this one been fixed ? If so, could you add a note to say how so that we know what to do it if it happens again.

**Comment by stvoutsin** [comment]
The issue was a type in the username/password combination when cloning the Github notebooks repo in Zeppelin
