### ISSUE TITLE
Exception when converting to Parquet from Zeppelin (Ceph permissions)

### ISSUE THREAD

**Issue by stvoutsin** [wfau/aglais#284]
**Description:**

Zeppelin is unable to create directories on the Ceph shares for nch, so the notebooks that convert to Parquet fail.

**Exception:**

```
Py4JJavaError: An error occurred while calling o1332.parquet. : org.apache.spark.SparkException: Job aborted.
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 56.0 failed 4 times, most recent failure: Lost task 0.3 in stage 56.0 (TID 70764, worker02, executor 4): java.io.IOException: Mkdirs failed to create file:/user/nch/PARQUET/TESTS/GEDR3/_temporary/0/_temporary/attempt_20201211143635_0056_m_000000_70764 (exists=false, cwd=file:/tmp/hadoop-fedora/nm-local-dir/usercache/fedora/appcache/application_1606774008678_0006/container_1606774008678_0006_01_000005)
```

**Code:**
```
%pyspark

# test reformat Gaia EDR3

from pyspark.sql import *

gaia_source_df = sqlContext.read.option('header', 'true').schema(gaia_source_schema).csv('file:////user/nch/CSV/GEDR3/GaiaSource_000000-003111.csv')
gaia_source_df.write.mode('overwrite').parquet('file:///user/nch/PARQUET/TESTS/GEDR3')
```

**Comment by stvoutsin** [comment]
What permissions do the (nch) directories on Ceph have?

ls -al /user/nch/

drwxrwxr-x. 6   1001   1001 2725293910766 Dec  1 14:02 CSV
drwxrwxr-x. 3   1001   1001             0 Dec 11 13:55 PARQUET
-rw-rw-r--. 1 fedora fedora           401 Oct 30 14:28 test.log

If we change those to 1001:fedora can we write to them?

`chown 1001:fedora PARQUET/
`

Writing from Zeppelin to Ceph now works, and so does nch's conversion notebook.

**Comment by Zarquan** [comment]
Discussion about how we manage user accounts and UIDs going forward ..

**Comment by stvoutsin** [comment]
It sounds like this is no longer an issue, as we've been running the conversions without this issue. Closing for now, we can reopen if it is still an issue, or occurs again.
