### ISSUE TITLE
[Bug] Zeppelin not being able to run any Spark jobs, can't find temp files under /tmp.

### ISSUE THREAD

**Issue by stvoutsin** [wfau/aglais#287]
**Description:**
Occasionally occuring exception in Zeppelin (pyspark) cells, where the exeption refers to not being able to find a file or directory, in  path that looks like this: "/tmp/hadoop-fedora/nm-local-dir/usercache/...". Has occured multiple times in our prototype which is deployed with Hadoop/Spark/Zeppelin using Ansible scripts as described here:  https://github.com/wfau/aglais/blob/master/notes/stv/20201130-ansible-deploy-hadoop-zeppelin-02.txt

**Exception:**
`Py4JJavaError: An error occurred while calling o1716.count. : org.apache.spark.SparkException: Job aborted due to stage failure: Task 9 in stage 91.0 failed 4 times, most recent failure: Lost task 9.3 in stage 91.0 (TID 106587, worker03, executor 3): java.io.FileNotFoundException: /tmp/hadoop-fedora/nm-local-dir/usercache/fedora/appcache/application_1606774008678_0006/blockmgr-a8ef4648-37f8-4cf5-ae28-5a0f7181f0c6/0c/shuffle_10_9_0.index.6f4f72ac-f6e6-40e8-8431-6f79b3d769e9 (No such file or directory)`

**Potential causes:**
"It is due to the tmpwatch utility, which runs daily on CentOS systems to clean up /tmp/files not recently accessed. The NodeManager service will not recreate the top level hadoop.tmp.dir (which defaults to /tmp/hadoop-${user.name}) when it launches a job."

**Potential fixes**
_Option -1_: Go to /etc/cron.daily/tmp-watch and exclude this directory from cleaning up daily. /tmp/hadoop-mapr/nm-local-dir/filecache
_Option -2_: Go to core-site.xml and add/change value of hadoop.tmp.dir property --- default is /tmp/hadoop-${user.name}
or yarn-site.xml and add/change value of yarn.nodemanager.local-dirs property --- default is ${hadoop.tmp.dir}/nm-local-dir

**Links:**
Notebook: http://zeppelin.aglais.uk:8080/#/notebook/2FV6XCUYT
StackOverflow link on issue: https://stackoverflow.com/questions/41881343/spark-yarn-tmp-no-such-file-or-directory

**Comment by NigelHambly** [comment]
It's happened again with the (non-AXS) small auto-deployment test platform:
<pre>
Py4JJavaError: An error occurred while calling o2380.fit.: org.apache.spark.SparkException: 
Job aborted due to stage failure: Task 2485 in stage 236.0 failed 4 times, most recent failure: Lost task 2485.4 in stage 236.0 (TID 877491, worker05, executor 11): java.io.IOException: No space left on device
</pre>

**Comment by stvoutsin** [comment]
This has been fixed by moving the Hadoop/Yarn temporary storage directory from /tmp to a Cinder volume:
https://github.com/wfau/aglais/pull/418
