### ISSUE TITLE
Test to verify astroquery and astropy are installed

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#300]
Create test notebooks to verify that astroquery and astropy are installed correctly.

**Comment by stvoutsin** [comment]
Simple test to check these libraries (with the expected versions) are installed here: https://raw.githubusercontent.com/wfau/aglais-testing/main/notebooks/Library%20validation.json
Plan is to update this repo to have test notebooks & include it as a test in the Ansible automated deploy

**Comment by Zarquan** [comment]
>  Plan is to update this repo to have test notebooks & include it as a test in the Ansible automated deploy

We either need to keep this issue open, or create a new one _"Include tests to validate Python library versions as part of standard deployment process"_. We need to keep something open to keep track of this until the tests are actually actively used as part of a standard deployment.  
If we close this one without opening another one there is a danger that the issue gets forgotten.
