### ISSUE TITLE
Copy parquet formatted files from nch test space to final, official location

### ISSUE THREAD

**Issue by NigelHambly** [wfau/aglais#304]
Bulk parquet ingests complete and validated. Sizes are:
[nch@aglais-20201130-zeppelin TESTS]$ du -h 
343G	./ALLWISE
37G	        ./2MASS
273G	./PS1
537G	./GEDR3
1.2T	.
[nch@aglais-20201130-zeppelin TESTS]$ pwd
/user/nch/PARQUET/TESTS

These are now ready to be copied to an official, permanent location.

**Comment by Zarquan** [comment]
Just to check the directory structure we want for this: 
```
    /data
       |
       +-- gaia
       |    |
       |    +-- dr2
       |    |    |
       |    |    +-- xxxxxx
       |    |    \-- xxxxxx
       |    |
       |    \-- edr3
       |         |
       |         +-- xxxxxx
       |         \-- xxxxxx
       |
       +-- panstarrs
       |    |
       |    \-- dr1
       |         |
       |         +-- xxxxxx
       |         \-- xxxxxx
       |
       +-- twomass
       |    |
       |    \-- allsky
       |         |
       |         +-- xxxxxx
       |         \-- xxxxxx
       |   
       +-- wise
            |
            \-- allwise
                 |
                 +-- xxxxxx
                 \-- xxxxxx
```

**Comment by NigelHambly** [comment]
Directory structure looks fine to me thanks.

**Comment by NigelHambly** [comment]
One doubt: if we get AXS up and running, we'll create new versions of the original parquet formatted catalogues bucketted by declination zone. Should we allow for these to be present in parallel to, or in sibling folders in each case, or ...
