### ISSUE TITLE
Zeppelin import notebook fails with 1MB exceeded exception

### ISSUE THREAD

**Issue by NigelHambly** [wfau/aglais#338]
A few of our science workflow notebooks are large, especially when they contain plots. The "Import notebook" facility in the Zeppelin UI will export such notebooks, but will not re-import them back if they exceed an apparently arbitrary default limit of 1MB. This really needs to be increased. I suggest at least 10MB, and if Zeppelin can handle it, even 100MB would not be unreasonable.

**Comment by Zarquan** [comment]
I think this is solved by PR #359, but we still need to deploy onto the live server.

**Comment by Zarquan** [comment]
This would have been deployed when we updated the live system to use the medium nodes.
