### ISSUE TITLE
VM Access issues when restarting Hadoop

### ISSUE THREAD

**Issue by stvoutsin** [wfau/aglais#339]
**Description:**
Restarting live & test services shows problems with master node accessing certain worker nodes

**Date**
February 2nd 2021, 17:20 BST

**Symptoms**

Try restarting Hadoop
fedora@master01

stop-all.sh 
Stopping namenodes on [master01]
Stopping datanodes
worker03: fedora@worker03: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
Stopping secondary namenodes [aglais-20210122-master01.novalocal]
aglais-20210122-master01.novalocal: fedora@aglais-20210122-master01.novalocal: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
Stopping nodemanagers
worker03: fedora@worker03: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
Stopping resourcemanager

start-all.sh 
Starting namenodes on [master01]
Starting datanodes
worker03: fedora@worker03: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
Starting secondary namenodes [aglais-20210122-master01.novalocal]
aglais-20210122-master01.novalocal: fedora@aglais-20210122-master01.novalocal: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
Starting resourcemanager
Starting nodemanagers
worker03: fedora@worker03: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).

**Attempts at a fix:**
Master01 node cannot ssh into worker03 node.
Worker03 .ssh/authorized_keys seems to be missing the keys for fedora@master01 & fedora@master02 that the other worker nodes have. 
After adding the keys to worker03, we can ssh into it. 
However it looks like the hadoop directories are missing. So most likely at deploy time there was an issue with worker03 that we missed, which means that the Ansible steps that create spark and hadoop did not successfully complete.

**Todo**
Try another deploy and see if all worker nodes are created without a problem.

**Comment by Zarquan** [comment]
What tests do we need to add to the deployment process to detect this and prevent us creating a non-functional system ?

**Comment by Zarquan** [comment]
Did the system work at all with this much missing ?

**Comment by stvoutsin** [comment]
Looks like this is addressed and no longer an issue: https://github.com/wfau/aglais/issues/340
