### ISSUE TITLE
Increase size limit for notebook uploads (Zeppelin)

### ISSUE THREAD

**Issue by stvoutsin** [wfau/aglais#356]
WIth the current setup the maximum allowed size for an uploaded notebook is 1 Mb.
We need to find where to change this, then modify our Ansible scripts to include the change, and finally redeploy

**Comment by Zarquan** [comment]
I think this was solved by PR #359

**Comment by Zarquan** [comment]
OK - we still need to do the deploy though.

**Comment by Zarquan** [comment]
Linking this to issue #338

**Comment by Zarquan** [comment]
This would have been deployed when we updated the live system to use the medium nodes.

**Comment by Zarquan** [comment]
This has been deployed to the live server.
