### ISSUE TITLE
Deploy Prometheus monitoring

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#384]
We need to have something to provide access to system level metrics to monitor what the system is doing. The effect of different caching options in our PySpark code only show up when we can monitor what the system is doing. 

Running `htop` on each of the VMs directly is one way of monitoring the activity, but it doesn't scale to multiple people monitoring multiple nodes and it doesn't record the history.

**Comment by Zarquan** [comment]
This needs to be integrated into our create-all and delete-all scripts.
Using Ansible to deploy the Prometheus data monitoring tools on all of our machines and using Ansible to create and configure the data collecting, visualisation and analysis tools on a separate VM.

**Comment by stvoutsin** [comment]
See https://github.com/wfau/aglais/pull/480
