### ISSUE TITLE
Check if we are running Spark in client mode or local mode

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#393]
From the Zeppelin documentation:
> _"Yarn client mode and local mode will run driver in the same machine with zeppelin server, this would be dangerous for production. Because it may run out of memory when there's many spark interpreters running at the same time. So we suggest you only allow yarn-cluster mode via setting zeppelin.spark.only_yarn_cluster in zeppelin-site.xml."_
-- [Spark Interpreter for Apache Zeppelin](https://zeppelin.apache.org/docs/latest/interpreter/spark.html)

**Comment by Zarquan** [comment]
I think we are running in one or other of these modes at the moment, because a lot of the Spark job coordination stuff appears in the spark interpreter logs on the Zeppelin node.

If we stick with the Ansible deployed Hadoop/Yarn system, then we probably need to look at integrating [Apache Livy](https://livy.apache.org/) into the mix.

**Comment by stvoutsin** [comment]
Currently we run in client mode (see: https://github.com/wfau/aglais/blob/master/deployments/hadoop-yarn/ansible/27-install-zeppelin.yml#L278)

There is a separate task to look into Livy, which sounds like a good solution to several issues.

**Comment by Zarquan** [comment]
Before we close this we should probably create a new issue to try running Spark in cluster mode and see if that works.

**Comment by Zarquan** [comment]
Closing this because I don't think this is going anywhere.
I suspect it will come up again when we try to run serious Python tasks on the Zeppelin node.
