### ISSUE TITLE
Template form for benchmarks

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#41]
As we add more benchmark tests we need to be sure we are being consistent.
This task is to create some kind of standard layout that we use to state the conditions of each test that we run.

* Test date : 2020-01-22
* Cloud name : cumulus, gaia-dev
* Number of workers: ...
* Cores per worker: ...
* Memory per worker: ...
... etc

**Comment by Zarquan** [comment]
Possibly with some Python or bash code that uses the openstack-client to fetch the details automatically each time ?

**Comment by Zarquan** [comment]
The automated code is later. This issue is just to write down a standard machine readable block of text that describes the system. (possibly JSON?)

**Comment by stvoutsin** [comment]
Some notes on a few benchmark tests that we can start with.
    https://github.com/stvoutsin/aglais/commit/a7677427f53ac97a7b05e4833b60f1c52136fc67
Plan is to take what is there and create a configuration template, and the tests as Python (pyunit?) files

**Comment by stvoutsin** [comment]
I've added some unit tests for testing out a Spark cluster with PySpark:
https://github.com/stvoutsin/aglais/commit/7dfc648dbf85707db552092e21a209d95ad7bf4e

There are three unit tests in the above commit, one for asserting Validity of output of a word count, and two for asserting timing of a Spark job.

The above is work in progress, so lots more to add..

**Comment by stvoutsin** [comment]
I suggest that we move the testing suit that we build, along with the configurations that we build into a new project

**Comment by Zarquan** [comment]
Done
