### ISSUE TITLE
Generate import schema from Gaia data model

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#42]
We have an initial version of the csv->parquet conversion schema as a [text file](https://github.com/wfau/aglais/blob/master/notes/stv/20200109-csv-schema.txt).

Following up on Nigel's comment to [issue 31](https://github.com/wfau/aglais/issues/31#issuecomment-572514584), we should find a way of generating our conversion schema from the Gaia data model.

**Comment by Zarquan** [comment]
@NigelHambly Given we have already imported eDR3 into Parquet - do we need this ?

**Comment by NigelHambly** [comment]
Schema generation code (takes WFAU MS SQL table creation script as input, and outputs the pyspark schema structure) is available in the DPAC SVN at

https://gaia.esac.esa.int/dpacsvn/DPAC_branches/CU5/software/personal/nhambly/ReformattingTools/src/exec/MakeParquetSchemaStructPy.java

and the Zeppelin ingestion notebook that employs this is available at 

https://gaia.esac.esa.int/dpacsvn/DPAC_branches/CU9/docs/personal/nhambly/ZeppelinNotebooks/Bulk%20data%20loading.json

This can be closed.
