### ISSUE TITLE
Live service down

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#437]
Live service unavailable - unknown how long it has been down

* 2021/04/20-17:56 Email report from Nigel that the live service is unavailable.
* 2021/04/20-18:32 Follow up from Stelios reporting unable to connect via `ssh`
* 2021/04/20-19:06 Follow up from Dave with debug showing DNS name resolves
  * ssh service not responding on port 22
  * Zeppelin service not responding on port 8080

* 2021/04/20-19:15 Logged in the Horizon user interface and  checked the status of the VMs
  * IP address given by DNS matches the floating IP address assigned to the Zeppelin node
  * Unable to connect to the Zeppelin VM using the console from the Horizon inferface
  * workers 04, 03, 02 and master 01 all respond OK to the Horizon console
  * Unable to connect to worker-01 and zeppelin
  * Unable to display log for worker-01 and zeppelin

**Comment by Zarquan** [comment]
* 2021/04/20-19:28 Tried a soft reboot of the zeppelin node from the Horizon interface
* 2021/04/20-19:32 Soft reboot failed to restart the service.

**Comment by Zarquan** [comment]
* 2021/04/20-19:36 Tried a hard shutdown of the zeppelin node from the Horizon interface
> Error: Unable to shut off instance: gaia-prod-20210324-zeppelin

**Comment by Zarquan** [comment]
* 2021/04/20-19:37 zeppelin instance is still stuck in `rebooting` sequence

**Comment by Zarquan** [comment]
OK - next steps will be :
* Create a new gateway VM on the same internal network, add a new floating IP address and try using that to login to the master node.
* Once we get access to the master node, we need to check that the newly partitioned data that Nigel generated has been copied from the HDFS system to the CephFS share mounted on `/user/nch`.
* If the Zeppelin node isn't responding then we can't check for recent changes to the notebooks.
* Unless there is anything more we can get from the remaining active nodes, nuke the lot and start again?

**Comment by stvoutsin** [comment]
- 2021/04/20-20:08 Created a _tiny_  node on the same project (prod) and assigned a floating IP address to it. I then tried accessing it via ssh, and got the same errors:
```
debug1: connect to address 128.232.227.212 port 22: Connection timed out
ssh: connect to host 128.232.227.212 port 22: Connection timed out
```
I also tried running the Ansible deploy on _test_ and this gets stuck at the following stage:

```

---- ---- ----
File [create-all.sh]
Path [/deployments/hadoop-yarn/bin]
Tree [/deployments]
---- ---- ----
Config yml [/tmp/aglais-config.yml]
Cloud name [gaia-test]
Build name [aglais-20210420]
Deployment [gaia-test-20210420]
---- ---- ----

---- ----
Running Ansible deploy
/deployments/hadoop-yarn/ansible /

PLAY [Install our public ssh keys] **************************************************************************************************************************************************************************

TASK [Create our Openstack key pair] ************************************************************************************************************************************************************************
changed: [localhost]

PLAY [Create our internal network] **************************************************************************************************************************************************************************

TASK [Create our internal network] **************************************************************************************************************************************************************************

```

**Comment by stvoutsin** [comment]
- 2021/04/21 19:38 Service has been recreated based on notes which are in a PR here: https://github.com/wfau/aglais/pull/441
Remaining task is to change the DNS entry to point to the new IP: 128.232.227.230

**Comment by Zarquan** [comment]
DNS entry updated.
Ran a quick test to check I could login and run a notebook.
Sky counts map works, but I needed to update the data source.

    - df = sqlContext.read.parquet("/hadoop/gaia/parquet/gdr2/gaia_source/*.parquet").select("source_id")
    + df = sqlContext.read.parquet("file:///data/gaia/edr3/").select("source_id")

**Comment by Zarquan** [comment]
Two new issue resulting from this
* Need to automate the DNS update #442 
* Update the front page notebooks #443
