### ISSUE TITLE
Export a notebook as an executable Python program

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#52]
Export a notebook as an executable Python program
Future issues will address where the program can be run from, how to import all the required libraries and what happens to the original notebook text.

**Comment by stvoutsin** [comment]
I've written a small Python library that converts a Zeppelin notebook into a Python program, which can be found here: https://github.com/stvoutsin/zeppelinTo
However integrating this into Zeppelin probably is not trivial, and possibly not in the scope of our short term plans.

**Comment by Zarquan** [comment]
This would be nice, but is it necessary at the moment ?
