### ISSUE TITLE
Transition to an ac.uk domain name

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#533]
At some point we will need to transition from our current `aglais.uk` domain to an `ac.uk` domain name.

**Comment by Zarquan** [comment]
Need to figure out how to make this dynamically update-able from our deployment scripts.

Current method is to make the main DNS entries CNAME references to entries in a DNS server that we control so that we can update the A records whenever we do a new deployment.

Unlikely that an existing ac.uk name provider would let us do that.

There was some discussion with John Garbutt about someone in the cloud community providing a DNS service for cloud instances, possibly StackHPC, Cambridge or IRIS, but no concrete plans yet.

**Comment by Zarquan** [comment]
Yep, that would work.
Do we have a technical person we can contact to find out if they would allow us to create CNAME aliases in their domain to point to our services ?

**Comment by NigelHambly** [comment]
I'll contact Cambridge on our behalf. 

Self-assigned for now.

**Comment by NigelHambly** [comment]
I've been in touch with Cambs in this regard. They're looking into the use of a sub-domain of gaia.ac.uk, viz. dmp.gaia.ac.uk from both technical and administrative standpoints. They've offered to pay for any DNS registration charges as well since they look after the same for gaia.ac.uk.

**Comment by NigelHambly** [comment]
Cambs says no problem: "This is easy enough to do. We have full access to the domain records so yes, a CNAME can be used. I just need the details for setting up the name."

@Zarquan : please provide "details for setting up the name" (whatever they may be!).

**Comment by Zarquan** [comment]
I think we just need them to add one CNAME alias record. 
````
dmp.gaia.ac.uk.	CNAME	aglais-live.duckdns.org.
````
if you want the long form
````
data-mining.gaia.ac.uk.	CNAME	aglais-live.duckdns.org.
````

The  CNAME (aliases) all point to our A record, `aglais-live.duckdns.org`, which we will update each time we do a new deployment.

**Comment by NigelHambly** [comment]
Thanks: dmp.gaia.ac.uk / aglais-live.duckdns.org it is.

**Comment by NigelHambly** [comment]
The subdomain was added this morning. However the person who set it up said that it looks like any server which uses the JISC zone files has the wrong CNAME and the one that use normal lookups are okay. As the JISC PDC service has the correct DNS it is hoped this will fix itself in around 14 hours.

**Comment by Zarquan** [comment]
Looks good to me
````
dig dmp.gaia.ac.uk

    ;; ANSWER SECTION:
    dmp.gaia.ac.uk.              50400    IN    CNAME    aglais-live.duckdns.org.
    aglais-live.duckdns.org.  60          IN    A              128.232.222.206
````

**Comment by Zarquan** [comment]
Looks good in web browser

http://dmp.gaia.ac.uk:8080/#/

Call this one done ?

**Comment by NigelHambly** [comment]
Yep seems fine to me!
