### ISSUE TITLE
Import notebooks from GitHub

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#55]
Initial step of importing notebooks from a publicly readable GitHib repository.

**Comment by NigelHambly** [comment]
This is available on the front page of the Zeppelin interface. No action needed.

**Comment by Zarquan** [comment]
Looks like this is done.

**Comment by Zarquan** [comment]
Not done - I mis-read the title.

**Comment by stvoutsin** [comment]
Could we get some more context on this issue? 
What Nigel was referring to, is that on the main page of Zeppelin you can import a notebook from a URL, so the basic functionality of importing from Github can be done. Is this task to do something more than that?

**Comment by NigelHambly** [comment]
I guess that's basically true, except that the spirit of this is to be able to easily preserve work outside of this cloud-based platform. As far as I can see I can export a json file to my local disk, I can then stick that in a repository from there. Furthermore I assume I can then import back via the URL option in the import note (correct? I haven't tried). But the former is one hop too many from a lazy person's viewpoint. I'd like to be able to import/export easily from/to the my external repository if possible.

**Comment by Zarquan** [comment]
What I had in mind having an 'import from GitHub' button that enabled you browse and pull notebooks from GitHub without having to explicitly copy/paste URLs. Longer term goal of being able to link your account with your GitHub account and then be able to import and export to/from a GitHub repository.

**Comment by Zarquan** [comment]
Example of this is the GitHub integration in Overleaf.

**Comment by Zarquan** [comment]
https://en.wikipedia.org/wiki/OAuth

**Comment by Zarquan** [comment]
Ok, so to be able to move this on, do we split it into stages ?

1. Import from URL (copy/paste)
1. Import from GitHub, read only (public repo, git clone) 
1. Register with GitHub as an OAuth application 
1. Import/export from GitHub, read/write (OAuth application)

What do we want to see in the GUI at each stage ?

**Comment by NigelHambly** [comment]
As mentioned during our last catch-up, at this stage I'd like to establish a road map to getting from where we are now to where we want to be at the end of this year, i.e. deployment of a reasonably user-friendly, stable system that friendly UK-based astronomers can try out. Broad concept of the top level look-and-feel of any GUI should come first, and could be included in such a road map. No harm in rapping over gory details at this stage, but I'd like to see the road map in place asap.

**Comment by Zarquan** [comment]
If we are going to have a separate web interface for Aglais, a landing website where users manage their accounts and bookings, then the GitHug integration would be part of that.
The outline and screen shots are still applicable, just as part of the Aglais pages not the Zeppelin pages.

**Comment by Zarquan** [comment]
Not a priority for the December release.

**Comment by Zarquan** [comment]
OK - looks like this might be important for December so I'm re-opening it.

**Comment by Zarquan** [comment]
The hope is that a lot of this functionality is now available in Zeppelin. So first part of this task is to look at what is available _"out of the box"_ in Zeppelin.

**Comment by Zarquan** [comment]
Looks like the Zeppelin functionality attaches a single GitHub account for all the notebooks.
We haven't found a way of doing this on a per user basis yet.

**Comment by Zarquan** [comment]
Been there, done that.
