### ISSUE TITLE
Add GaiaXPy to the imported modules

### ISSUE THREAD

**Issue by NigelHambly** [wfau/aglais#574]
CU5 in Cambridge have produced a python module for working with the XP low res spectrophotometry that is being released as part of DR3. See

https://wiki.cosmos.esa.int/gaia-dpac/index.php/CU5:_Photometric_Processing:_Tools:_GaiaXPy

on the DPAC wiki for general details, but more specifically see the DPAC svn project

https://gaia.esac.esa.int/dpacsvn/DPAC/DPCI/software/tools/GaiaXPy/

where installation instructions are given under

https://gaia.esac.esa.int/dpacsvn/DPAC/DPCI/software/tools/GaiaXPy/README.md

Can this python module be included in the standard deployment?

**Comment by Zarquan** [comment]
Is the source code available somewhere public without requiring a gaia svn login ?
If it is public we can add it to our automated build.
If it needs a username:password login to get the source code, then it makes it harder to automate the install.

**Comment by Zarquan** [comment]
If it isn't public, then are there restrictions on us making it available to non-dpac users ?

**Comment by NigelHambly** [comment]
er.... good point. Presently it's behind DPAC credentials so I guess we'd have to ask for permission to deploy on the understanding that we won't distribute it further, and only me, you, Stelios and Dennis will play with it (we're all DPAC CU9). I'll raise a DPAC jira and ask.

**Comment by NigelHambly** [comment]
Cambridge are OK with us installing the SW. Note we should use SVN revision 727059. It's not available publicly yet, and should not be staged anywhere public (of course) as part of any deploy we do.  As long as there are no non-DPAC users of the platform this is OK for now. If/when we do open up, then we need to revisit with Cambridge what to do at that time (they may already have made a public release of their SW anyway).

**Comment by Zarquan** [comment]
Done - we are using it in examples.
