### ISSUE TITLE
Permission to use Gaia eDR3 in ESCAPE

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#582]
I would like to use the Parquet version of Gaia eDR3 as a test case in the ESCAPE / EOSC cloud system.

We need a hard use case for data management in the ESCAPE project. An example that needs to bring data and code together on a cloud compute platform.

The Gaia eDR3 data and a K8s version of our analysis platform would be an ideal use case. We are already familiar with both the data and the analysis code, making it a ready made example for us to work with.

If it worked, then ESCAPE would get a strong use case to demonstrate their system, and DPAC would get another platform for analysing Gaia data.

It would be good to get approval from someone in Gaia/DPAC/ESCAPE before going ahead with this.

Who should I talk to ?

**Comment by NigelHambly** [comment]
No worries - always worth a check when you're uncertain about these things. But don't worry: EDR3 is in the public domain now, and anybody can do anything they like with it.

**Comment by NigelHambly** [comment]
Closing this for tidiness.
