### ISSUE TITLE
Hard coded user account

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#59]
A single hard coded user account and password, managed manually.

**Comment by Zarquan** [comment]
This is what we have now. Although we need some notes on how to manage the account and change the password.

**Comment by Zarquan** [comment]
@stvoutsin Can we document how to set the username and password for this.

**Comment by Zarquan** [comment]
These are notes on how to set it up to start with, which is different to how to maintain it. It also isn't clear which machine this needs to be run on.

If we needed to change the user name or password, tomorrow, on the existing running cluster, which machine do we login to, what file do we need to edit, and how do we get Zeppelin to recognise the change ?

**Comment by Zarquan** [comment]
We probably need to check we all have ssh access to the machines as well. Ideally, if one of us is away, then someone else on the team can jump in and administer the cluster.

https://en.wikipedia.org/wiki/Bus_factor

**Comment by stvoutsin** [comment]
Some notes on creating new users (or modifying existing) here: https://github.com/stvoutsin/aglais/blob/cf6e82b9efaaa08b14a94bd430b350c82a63dd65/notes/stv/20190428-zepellin-users.txt

@Zarquan Your pub key is under the authorized keys so you should have access to all of the machines on the current prototype. If not let me know and I can have a look.
