### ISSUE TITLE
Revisit Zeppelin user permissions 

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#594]
PR #590 has the following comment in `notes/stv/20211013-Spark3-zeppelin-0.10.0-permission-issue.txt` in 

> After some investigation, it looks like the new Zeppelin runs Spark jobs as the logged in Zeppelin user, and fails because it lacks permission.
> Turn this off for now, so that everything is sent as the main Zeppelin user (After this change Spark notebooks work)

We need to re-visit this, document what happens when it is turned ON, and decide if this is useful for us.
I suspect it will be useful, but it will need changes to the rest of the system.

**Comment by Zarquan** [comment]
Revisit with what we know about impersonation.

**Comment by NigelHambly** [comment]
On the existing live system dmp.gaia.ac.uk as user nch I don't seem to be able to write outputs to my own folders /home/nch or /user/nch:

dataframe.write.csv('/user/nch/2MASSJ00531123+6730023-GaiaXPSpectrum.csv')

results in

Py4JJavaError: An error occurred while calling o1550.csv.
: org.apache.hadoop.security.AccessControlException: Permission denied: user=nch, access=WRITE, inode="/":fedora:supergroup:drwxr-xr-x

 and the same for /home/nch.

**Comment by Zarquan** [comment]
OK, checking to see what is causing this.

**Comment by Zarquan** [comment]
Quick fix add the filesystem prefix to the file path
```
write.csv('/user/nch/2MASSJ00531123+6730023-GaiaXPSpectrum.csv')
```
becomes
```
write.csv('file:///user/nch/2MASSJ00531123+6730023-GaiaXPSpectrum.csv')
```
note it needs three '/'s.

That will get your notebook to work and saves the data as a directory of 300 csv files (~2.4M bytes) you can download and use.

**Comment by Zarquan** [comment]
Tried a similar write operation on green and got the same result. So this isn't a difference between green and blue.

**Comment by Zarquan** [comment]
Quick look at some of the DR3 ingest notebooks, and the ones I looked at all use `file:///` prefix for the read and write operations.

I think what is happening is that Spark defaults to using the `hdfs://` file-system unless we specify the linux file-system using the `file:///` prefix. At some point in the past I remember we set the default location to be `file:///` rather than `hdfs://` so this is a regression. This issue also implies that we don't have permission to write to the `hdfs://` file-system, which is another regression.

**Comment by NigelHambly** [comment]
Oh yes this rings a bell. Interestingly if I use the pandas data frame.to_csv method having first collected the DF to a pandas DF it does what I want, i.e. write a single csv of the data as collected to the driver. The data from the spark DF write csv is useless as it's one (largely empty) csv file per partition...!

**Comment by Zarquan** [comment]
Two new issues to fix the details
* #854 
* #855

**Comment by Zarquan** [comment]
Added a new tag 'live-users' to indicate things we need to fix asap to avoid confusing our new users with junk like the right number of '/'s in `file:///` just to save a file.

**Comment by Zarquan** [comment]
Are we OK for this evening ?

**Comment by Zarquan** [comment]
I think this is done now.
