### ISSUE TITLE
Setup tables for 2mass, PanSTARRS and Wise

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#605]
The example setup notebook creates a database and tables for gaiaedr3 gaia_source and the neighbour tables, but it doesn't create databases or tables for the other catalogs that the neighbour tables link to.

Do we need to create databases and tables for 2mass, PanSTARRS and Wise ?

    # show the database(s) now available within the context
    spark.sql("show databases").show()

    +------------+
    |databaseName|
    +------------+
    |     default|
    |    gaiaedr3|
    +------------+

    # show the contents of the catalogue store that has been set up
    spark.catalog.listTables()

    [
    Table(name='gaia_source', database='gaiaedr3', ....
    Table(name='gaia_source_allwise_best_neighbours', database='gaiaedr3', ....
    Table(name='gaia_source_ps1_best_neighbours', database='gaiaedr3', ....
    Table(name='gaia_source_tmasspsc_best_neighbours', database='gaiaedr3', ....
    ]

**Comment by NigelHambly** [comment]
No need - those gaia_source_* tables contain the attributes from the external surveys already (see AglaisPublicExamples/Data holdings notebook for an explanation).
