### ISSUE TITLE
Examples for cross match with 2mass, PanSTARRS and Wise

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#606]
The _"AglaisPublicExamples/Data holdings"_ notebook talks about the best neighbour tables, but as far as I can tell we don't have an example notebook showing how to create a join query that uses them.

**Comment by NigelHambly** [comment]
I'll see to this ... in the fullness of time.

**Comment by NigelHambly** [comment]
New notebook added "6. Working with cross-matched surveys". Just needs a few small tweaks and polishing when full DR3 arrives.
