### ISSUE TITLE
Create draft landing pages for the Gaia Data Mining Platform on the Wiki

### ISSUE THREAD

**Issue by NigelHambly** [wfau/aglais#625]
As discussed at our last catch-up meeting, a brief set of static, landing web pages for our IRIS-hosted data mining platform service  should be drafted on the Wiki for the team to see and work on together (assignee to take the lead on drafting them). The pages should include
- basic information
- screenshot examples of the platform in use
- FAQ/trouble-shooting guide and contact-for-help
- information on obtaining access / web-form application for account etc.

The idea is these will then be copied off to a more permanent public place (e.g. gaia.ac.uk).

**Comment by NigelHambly** [comment]
Top page created at [https://github.com/wfau/aglais/wiki/Landing-pages]

**Comment by NigelHambly** [comment]
I've been in touch with Cambs as regards hosting these pages on gaia.ac.uk, which they are quite happy to do. 

The idea of an integrated web form for registration purposes won't fly though because the content management system they use doesn't have the necessary plug-ins for handling active pages. I suggest we follow the simple example of the WFAU infrared archive support system: a simple email end point (e.g. gaiadmp-support@roe.ac.uk) that we three subscribe to, that we put on the static web pages, as the email address users should send requests to for accounts and subsequent support requests. 

OK? Discuss.

**Comment by NigelHambly** [comment]
Alternatively could use Google forms. 

Personally I think I prefer the simplest solution: a central support email address for everything.

**Comment by Zarquan** [comment]
We own the domains aglais.uk, gaiadmp.uk and gaiamlp.uk. I could look at setting up a blanket forward, any emails sent to any address at those domains end up in one of our personal accounts.
That would enable us to put support@gaiadmp.uk, help@gaiadmp.uk etc on the webpage and they would arrive in our inbox.
That would do for a start, we could look at adding more structure later.

**Comment by Zarquan** [comment]
As a test I've added a blanket forwarding from anything@gaia-dmp.uk to Nigel's ROE address.
See if that is enough for now.

**Comment by NigelHambly** [comment]
As discussed I think it's best if we keep as simple as possible, with the flexibility for several destination email addresses (in case one or other of us is incapacitated) so I'll look into getting a gaiadmp-support@roe.ac.uk set up for us three.

**Comment by NigelHambly** [comment]
@Zarquan , @stvoutsin : I have created a final draft of the landing pages that I propose we put up on gaia.ac.uk - please see  [here](https://github.com/wfau/aglais/wiki/Landing-pages). 

If you can let me have comments and suggestions, say by the end of the month (i.e. by close of play next Tuesday) I will then arrange to have them staged statically on the UK Gaia web pages.

**Comment by Zarquan** [comment]
I've added a couple of suggestions to the first section. 
I think it needs to be more positive and promote/define GaiaDMp in terms of what GaiaDMp **can** do, rather than what other tools like relational databases can't do.

**Comment by NigelHambly** [comment]
OK thanks - I've incorporated those. The page as it stands is being mirrored on gaia.ac.uk but not made public until we're ready (i.e. when I've pulled in all the DR3 data following public release next Monday). 

This ticket is done but I won't close until the page is published on gaia.ac.uk

**Comment by NigelHambly** [comment]
Published on gaia.ac.uk. All done.
