### ISSUE TITLE
Enable Arrow SQL execution (spark.sql.execution.arrow)

### ISSUE THREAD

**Issue by stvoutsin** [wfau/aglais#646]
Set spark.sql.execution.arrow.enabled = true in Spark configuration.
As reported by Nigel, for gaiaxpy & the DR3 data, it is required to enable arrow in Spark.
(See notebook: DR3 XP continuous spectra ingest test_2GXWQESPT.zpln in current deploy)

**Comment by stvoutsin** [comment]
Done in https://github.com/wfau/aglais/pull/675
Will be available in the next deploy

**Comment by NigelHambly** [comment]
I've just checked on a current deploy (green) via this:

spark.conf.get('spark.sql.execution.arrow.enabled')

and the return value is false, rather than true. Has this slipped through the net, despite the issue being closed?

**Comment by stvoutsin** [comment]
I've just checked and we set spark.sql.execution.arrow.pyspark.enabled = true
Should this be spark.sql.execution.arrow.enabled instead? I'll add this as a new issue. For the next deployment we'll set both parameter to true, and we can figure out which one is correct later

**Comment by NigelHambly** [comment]
Not sure sorry... may be noise as the point in my notebooks where I've noted it's necessary now doesn't seem to make any difference whether the property is true or false, with or without pyspark in the signature.

Nothing's broken so I'll close this and reopen if I find a problem with the set-up.

**Comment by NigelHambly** [comment]
Just to confirm (see #824) I was wrong (and not for the first time). Testing using public example 5 shows that the property signature should indeed half pyspark as the penultimate item and if it is false, the notebook stops working. So everything is fine as it is, and my apologies for the noise.
