### ISSUE TITLE
Remove hdbscan notebook from public examples

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#647]
Based on email conversations with Dennis is looks like it would be better to remove the `hdbscan` notebook from our public examples. At least until we have a better handle on how to limit the side effects on other users of it running out of memory.

**Comment by NigelHambly** [comment]
Suggestion is to limit the heavy non-distributed part to a smaller row set, add in caveats/warnings/annotations as to why the full-blown thing should not be attempted at this stage, and reinstate. It's worth including this in the example notebooks set as it contains useful illustration of sample selection with UDFs and is based on a real-world usage scenario.

**Comment by NigelHambly** [comment]
At this stage of the project it's probably a bit risky including this example as inevitably people will run it, possibly a lot, and even if descoped it could bring zeppelin to it's knees. It may be better not to include this example at this stage.

**Comment by Zarquan** [comment]
Done - HDBSCAN is not in the public examples.
