### ISSUE TITLE
Allow users to store data using Zeppelin (Persistent or Temporary Storage)

### ISSUE THREAD

**Issue by stvoutsin** [wfau/aglais#65]
We need to allow Zeppelin users to store data somewhere. 

Do we look into using HDFS for this as a first step? 
The Zeppelin node in the "production" service is very small so we can't use that most likely.

If we move to a service similar to what we have for lsst with Jupyter on K8s, and spawn new Zeppelin containers per user, we can allocate storage for those containers. Making it persistent probably is a longer term task though, as it would require us to setup user management / quotas / etc..

There is a requirement for persistent storage, but as a start temporary storage would work for helping our initial users develop notebooks, though persistent storage with HDFS might be easier to setup.

**Comment by Zarquan** [comment]
Using HDFS makes sense, as we can write direct to HDFS from the Spark nodes too.

We will probably keep at least some HDFS space available even if we move the main dataset elsewhere.

**Comment by stvoutsin** [comment]
I've created an HDFS directory for Zeppelin users to write files to for persistant storage.
- https://github.com/stvoutsin/aglais/commit/4114ecbfb463b6ca7e0797421444c8272174fb33

Nigel has tested and confirmed that writing files works, (as long as file doesn't already exist). Perhaps a follow up task would be to look into how to allow users to alter/rewrite existing files in HDFS, as if they run the same notebook which creates a file with the same name, this would produce an error.

**Comment by Zarquan** [comment]
HDFS filesystem is write once, read-only.

**Comment by Zarquan** [comment]
How do we progress this issue ?
Is it useful to split it into smaller steps that can be completed one at a time.
- Shared temp storage accessible to all users
  - HDFS temp space (create and append but not modify)
  - Network mounted temp space (normal filesystem)
- Per user storage, shared between notebooks, linked to the user account (user home directory)
  - HDFS user space (create and append but not modify)
  - Network mounted user space (normal filesystem)

Additional thoughts
- At what stage do we add configurable quotas to these ?
- Do we have a cron job cleaning old files from the temp spaces ?
- What level of backup/restore guarantees do we want to provide for the user space ?

**Comment by Zarquan** [comment]
Is this solved by using Manila shares (see #189) ?

**Comment by Zarquan** [comment]
Swapping between HDFS and network shared directories is confusing.
We are planning to allocate a shared directory for each user in `/users`, is this sufficient for DR3 ?

**Comment by Zarquan** [comment]
All users now get a 10Gbyte CephFS share.
