### ISSUE TITLE
Missing libraries in Python examples

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#650]
We have included the [_IPython Visualization Tutorial_](http://zeppelin.aglais.uk:8080/#/notebook/2F1S9ZY8Z) in our public examples, but the notebook refers to a number of modules that aren't loaded in our system, We should add the modules where possible. If we can't add the modules should we remove/disable the examples ?

* seaborn
* plotnine
* ggplot
* bokeh
* holoviews
* altair
* plotly

**Comment by NigelHambly** [comment]
Relevant operational stuff extracted into "tips and tricks" in public examples, and everything else scrubbed.
