### ISSUE TITLE
Review Spark interpreter notebook

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#652]
The [_Spark Interpreter Introduction_](http://zeppelin.aglais.uk:8080/#/notebook/2F8KN6TKK) notebook has a lot of examples of how to tweak the Spark configuration which probably aren't relevant. Should we remove this notebook from our public examples  ?

**Comment by NigelHambly** [comment]
Useful stuff extracted into "tips and tricks" in public examples, and everything else scrubbed.
