### ISSUE TITLE
Include error in Spark SQL example

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#654]
The _Create DataFrame via DataFrameReader_ section of the [_Spark SQL_](http://zeppelin.aglais.uk:8080/#/notebook/2EWM84JXA) notebook fails with an include error:
```
Fail to execute line 3: SPARK_HOME = os.getenv('SPARK_HOME')
Traceback (most recent call last):
  File "/tmp/1646748337192-0/zeppelin_python.py", line 153, in <module>
    exec(code, _zcUserQueryNameSpace)
  File "<stdin>", line 3, in <module>
NameError: name 'os' is not defined
```

**Comment by NigelHambly** [comment]
Relevant stuff extracted from tutorials into "tips and tricks" in public examples, and everything else scrubbed.
