### ISSUE TITLE
Missing data for Spark SQL example

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#655]
The _Create DataFrame via DataFrameReader_ section of the [_Spark SQL_](http://zeppelin.aglais.uk:8080/#/notebook/2EWM84JXA) notebook refers to example data that is not on the system.
```
java.io.FileNotFoundException: File file:/opt/spark/examples/src/main/resources/people.json does not exist
```

**Comment by NigelHambly** [comment]
No longer relevant - inoperative notebooks have been scrubbed.
