### ISSUE TITLE
Install custom Python libraries on Spark Cluster

### ISSUE THREAD

**Issue by stvoutsin** [wfau/aglais#67]
As an example, Nigel needs  HDBSCAN installed for the “Kounkel and Covey groups demo” notebook.

**Comment by stvoutsin** [comment]
This could be split into two tasks:

1. Install hdbcscan on existing Spark cluster to allow Nigel & Dennis to write their notebook.
2. Document and script the installation of all possible Py libraries

**Comment by Zarquan** [comment]
Agree with splitting this into separate tasks, one for N&D now and one for longer term.

**Comment by Zarquan** [comment]
Is it _'hdbcscan'_ or _'dbcscan'_ ?
Google finds lots for _'dbcscan'_ but nothing for _'hdbcscan'_, or is it a private library not yet published ?

- https://en.wikipedia.org/wiki/DBSCAN
- https://scikit-learn.org/stable/modules/generated/sklearn.cluster.DBSCAN.html

**Comment by stvoutsin** [comment]
Hdbscan is a library built ontop of dbscan as far as I can understand, looks like it does a similar thing using a slightly modified algorithm 
- https://hdbscan.readthedocs.io/en/latest/how_hdbscan_works.html

**Comment by stvoutsin** [comment]
I've installed hdbscan on the "production" service for Nigel & Dennis to use for now. I'll leave this issue open so that we can address the longer term task

**Comment by stvoutsin** [comment]
I think we an close this for now? There is nothing else to install on the live system, and we have a new issue open for the longer term task of the curated list of Python libs (#104)

**Comment by Zarquan** [comment]
Yep, agreed.
