### ISSUE TITLE
Cache directive in mean proper motions example 

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#670]
The mean proper motions example contains explicit cache commands.
```
df = spark.sql(query).cache()....
....
....
sqlContext.clearCache()
```

Do we need the explicit cache directives ?
What effect does this have in a multi-user environment, and do we want to encourage users to do this ?

We should create a test sequence with multiple users running this example concurrently with and without the cache directive to see what effect this has on the other users.

**Comment by NigelHambly** [comment]
See comments in #671

**Comment by Zarquan** [comment]
The costs and benefits of caching were discussed in #671, so closing this issue.
