### ISSUE TITLE
Enhance Gaia DMP set up for DR3

### ISSUE THREAD

**Issue by NigelHambly** [wfau/aglais#678]
Incorporate new DR3 schema info and split into top level plus EDR3 and DR3 individual set up scripts.

**Comment by NigelHambly** [comment]
Code project is [here](https://github.com/wfau/gaiadmpsetup).

**Comment by Zarquan** [comment]
What is the best way to test and merge this ?

Short form:
1. If we setup a test deployment of Zeppelin I think we can `pip install` the new version direct from your fork of [gaiadmpsetup](https://github.com/NigelHambly/gaiadmpsetup). @stvoutsin could you confirm this would work ?

Long way round :
1. If you create a new PullRequest from your fork of [gaiadmpsetup](https://github.com/NigelHambly/gaiadmpsetup) and ask @stvoutsin to review it.
2. The we can create a new release of the `gaiadmpsetup` library.
3. Which can then be installed on a deployment of Zeppelin using `pip`.

If the short form works it would give us a quick and easy way to test it before we go through the steps to create the `pip` installable library.

**Comment by NigelHambly** [comment]
Thanks: the former (short) would be a very good idea, not least because I've almost certainly munged something in my ham-fisted python  hacks... a quick validation would be very much appreciated.

**Comment by NigelHambly** [comment]
@stvoutsin and I have merged in the changes and a new patched library is installed on the live service. I've briefly tested (just verified imports) and everything seems to be in place for importing DR3 data starting next week.

This ticket is done but remains open until I've battle-tested the library with the full DR3 ingests.

**Comment by NigelHambly** [comment]
During DR3 ingest attempts a couple of bugs in the gdmp set-up library have come to light:

1. Boolean types in the DPAC DR3 data model schema are currently mapped to ByteType() resulting in csv parsing/conversion errors: these should be changed to (the appropriate) BooleanType() so that the true/false text values in the csv get correctly parsed;
2. gdmpstore module function create_interim_schema_for_csv() stupidly overwrites the given target schema resulting in string-expressed arrays in the csv being cast to strings and not floats as intended (i.e. the casting does nothing!).

These must be fixed pronto in my fork, a PR opened to merge them into the production for merging followed by a new patch release so that the current parquet ingests (using hacked versions in my DR3 ingest notebook) can be reattached as data resources in fresh spark contexts.

**Comment by NigelHambly** [comment]
Both 1. and 2. above fixed in personal fork - see

https://github.com/NigelHambly/gaiadmpsetup/commit/86868be6eb4548f7b6df55eeb5046d066521a546

Leaving this open in case any other bugs emerge during the DR3 ingest battle.

**Comment by Zarquan** [comment]
@NigelHambly Can we close this a done ?

**Comment by Zarquan** [comment]
This is done. Anthing new goes in follow-on issues
* #909
