### ISSUE TITLE
Deploy test version of seup library on live

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#711]

**Comment by Zarquan** [comment]
We haven't been able to leave a test systems running for long, which has prevented us configuring a test system to use for developing and debugging the setup library.

Plan is to edit the live system to deploy the setup library direct from git rather than using the released version.

Replace this (from `requirements.txt`):
```
    pip install 'git+https://github.com/wfau/gaiadmpsetup@v0.1.0'
```
with something like
```
   git clone 'https://github.com/wfau/gaiadmpsetup' '/var/local/gaiadmpsetup'
   pip install --editable '/var/local/gaiadmpsetup'
```

This will enable us to edit and test the `gaiadmpsetup` and ultimately push it back to the repository when we are happy with it.

**Comment by Zarquan** [comment]
Need to check on how Nigel has been editing his version of the library and see if we can configure something similar on the live server.

**Comment by Zarquan** [comment]
Having talked with Nigel, he is happy editing on his laptop and pushing the changes to his fork on GitHub.  In which case, possibly the best option would be to `pip install` Nigel's fork onto the live server. Then Nigel can edit on his laptop, push to GitHub and then execute `git pull` on the live server to download his changes.

**Comment by Zarquan** [comment]
Specifically, we would use Nigel's fork for this rather than the main repo.
```
    git clone 'https://github.com/NigelHambly/gaiadmpsetup' '/var/local/gaiadmpsetup'
    pip install --editable '/var/local/gaiadmpsetup'
```

Nigel can continue with what he is already doing, editing the code on his laptop and pushing the changes to his fork in GitHub.

Then we can update by doing
```
    cd '/var/local/gaiadmpsetup'
    git pull
```
either via a ssh connection, or from a `%sh` cell in a notebook ?

**Comment by Zarquan** [comment]
I think we decided at last telecon that since Nigel is the only person using the live system, and that because Dave and Stelios are regularly deleting and creating on the test clouds we are unlikely to have a stable test version in the next week or so. it would be OK to install Nigel's version on the live system so that he can work on it there.

**Comment by Zarquan** [comment]
If you have fixes since Nigel's PR then we can add them back into the main repo and then update Nigel's version with the fixes before we try installing it on the live system.

**Comment by Zarquan** [comment]
So the sequence would be ..
* Review & merge Stelios's PR https://github.com/wfau/gaiadmpsetup/pull/2
* Update Nigel's fork (using command line on his laptop is safer)
* Link the pip installed version on the live system to Nigel's fork (no branch)
* Check that Nigel can update using `git pull` or `pip install` from ssh login or in a notebook.
* Profit !??

**Comment by stvoutsin** [comment]
On Tuesday (24/05/2022) in a meeting between @NigelHambly  & myself we ran through the above process:

- Reviewed and merged PR https://github.com/wfau/gaiadmpsetup/pull/2
- Updated Nigel's fork 
- Created a new Release (https://github.com/wfau/gaiadmpsetup/releases/tag/v0.1.1)
- Installed new (patch) version on live deploy (install for all nodes)

Installation of new release was done with the following command:

**Comment by stvoutsin** [comment]
@Zarquan Are we happy to close this issue?

**Comment by Zarquan** [comment]
Yep, if Nigel is happy, I'm happy.
