### ISSUE TITLE
Move /user to /data

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#726]
At the moment we allocate each user a Linux home directory, `/home/<usernane>` and a data directory called `/user/<username>` on the Linux filesystem.

The Hadoop system also creates a directory on the HDFS filesystem for each user, used for passing code and data between the Spark Maser and the workers, the default name for which is `hdfs:///user/<username>`, or just `/user/<username>` if you are within Hadoop's scope.

So we have directories on the Linux file system and the HDFS filesystem with the same name. The computers handle this with no problem, but humans tend to get very confused.

To avoid confusion I have configured Hadoop to use a different name for now. However there may be cases where examples in the Hadoop or Spark documentation use the default name, which will no longer work.

I'd like to propose we move our user's data directories from `/user`, to `/data`, to be siblings of the gaia data.

```
/user
  |
  +-- nch
  +-- stv
  \-- zrq

/data
  |
  \-- gaia
```

becomes
```
/data
  |
  +-- nch
  +-- stv
  +-- zrq
  \-- gaia
```

We can make the re-assignment next time we do a deployment. It just needs a couple of fields changed in the configuration.

The only side effect I can think of will be that notebooks that write data to `/user/<username>` need to be changed to write data to `/data/<username>`.

It also means we can't have a user called `gaia`, but that is probably a good thing.

We can then revert the Hadoop settings to use the default `hdfs:///user/<username>` for the users's transfer directory so it will match the value given in the Hadoop and Spark documentation.

If you agree, please leave a comment with a :+1:

**Comment by stvoutsin** [comment]
+1

**Comment by NigelHambly** [comment]
:+1: fine by me!

**Comment by Zarquan** [comment]
OK, we will schedule this for the next round of development work.
I'll send an email reminder when it goes live.

**Comment by Zarquan** [comment]
Lots of last minute things got in the way and it is too late to try to make a possibly breaking change now.
