### ISSUE TITLE
Update benchmark system to handle trailing '/'

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#740]
The `AglaisBenchmarker` Python code is unable to cope with a trailing `/` on the Zeppelin endpoint.
This makes the test code very fragile and prone to errors.

This works
```
   endpoint = http://zeppelin:8080
```

This fails
```
   endpoint = http://zeppelin:8080/
```

Simple enough to detect the trailing `/` in `AglaisBenchmarker`, making it easier and more robust to use.

**Comment by stvoutsin** [comment]
Fixed in: https://github.com/wfau/aglais/pull/752 (Reopen if you think this is not the case)
