### ISSUE TITLE
Update AglaisBenchmarker to include delays

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#746]
Add two configurable delays to `AglaisBenchmarker`.
* Cumulative startup delay
* Pause between notebooks

The startup delay is cumulative. If the delay is set to 10s, then the first thread starts as normal, the second thread waits for 10s, the third thread waits for 20s, the fourth thread waits for 30s .. etc. This has the effect of gradually increasing the load rather than all of the threads attempting to start at the same time.

The pause between notebooks simply sleeps a set amount of time between completing one notebook and starting the next. Giving the system time to release and recover resources between executing notebooks.

**Comment by stvoutsin** [comment]
Fixed in: https://github.com/wfau/aglais/pull/752 (Reopen if you think this is not the case)
