### ISSUE TITLE
Add error handling to AglaisBenchmarker

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#769]
Dumping the contents of the stack trace into the output destroy any chance of JSON formatting it.
We need to add an error handler to AglaisBenchmarker that catches Exceptions and serialises the stack trace into a string suitable for including in the JSON output.

**Comment by Zarquan** [comment]
Links to associated issues:
* #741
* #602

**Comment by stvoutsin** [comment]
Fixed in: https://github.com/wfau/aglais/pull/752 (Reopen if you think this is not the case)
