### ISSUE TITLE
Structure test output as an array

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#776]
The output from the `AglaisBenchmarker` lists the results as a dictionary, using the notebook name as the element name.
```
{
"GaiaDMPSetup": {
    "result": "PASS",
    "outputs": {
        ....
        },
    "time": {
        ....
        },
    "logs": ""
    },
"Mean_proper_motions_over_the_sky": {
    "result": "PASS",
    "outputs": {
        ....
        },
    "time": {
        ....
        },
    "logs": ""
    },
    ...
}
```
This makes is hard to process the results to get aggregate results. We end up using complicated operations in `jq` to re-formatting the elements as an array.

Structuring the results as an array of similar elements would make it much easier to process.
```
[
    {
    "name":"GaiaDMPSetup",
    "result": "PASS",
    "outputs": {
        ....
        },
    "time": {
        ....
        },
    "logs": ""
    },
    {
    "name":"Mean_proper_motions_over_the_sky",
    "result": "PASS",
    "outputs": {
        ....
        },
    "time": {
        ....
        },
    "logs": ""
    },
  ...
]
```

**Comment by Zarquan** [comment]
A side effect of the current dictionary structure is that some JSON tools may re-order the elements based on the notebook name rather than chronological order of execution.

**Comment by stvoutsin** [comment]
Fixed in: https://github.com/wfau/aglais/pull/752 (Reopen if you think this is not the case)
