### ISSUE TITLE
Diagnose stalled transfer

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#789]
Email from Nigel:
>   I’m currently gunzipping the Gaia DR3 csv files. Something appears to have killed my nohup’ed recursive gunzip yesterday at around 17:14 UT … any ideas anybody?
I could set it going again and hope for the best, but I’m always a bit concerned when unexpected and unexplained things happen…
>
>   /user/nch/CSV/GDR3/nohup_gunzip.out
>
>   I arrowed both stdout and stderr to this log file but there’s no clue as to why it stopped.
>
>   Come to think of it: I’m doing this as fedora, not nch, albeit on volume /user/nch.
>
>   Dave: is it possible that a fedora quota policy is killing me?
>   Can either of you check system logs around that time: the process was running on the production system head, iris-gaia-green-20220405-zeppelin

**Comment by Zarquan** [comment]
Looks like this was solved by Stelios :+1: 

Email from Stelios:
> Not sure if you managed to get this working or not, but I've had a
> quick check of the system logs, and I noticed the following around the
> time where the nohup log was last modified:
> 
> Jun 20 17:14:31 iris-gaia-green-20220405-zeppelin sshd[473604]:
> pam_unix(sshd:session): session closed for user fedora
> ....
> Jun 20 17:14:31 iris-gaia-green-20220405-zeppelin
> systemd-logind[1101]: Session 109 logged out. Waiting for processes to
> exit.
> Jun 20 17:14:31 iris-gaia-green-20220405-zeppelin systemd[1]:
> session-109.scope: Succeeded.
> Jun 20 17:14:31 iris-gaia-green-20220405-zeppelin systemd[1]:
> session-109.scope: Consumed 1h 41min 4.618s CPU time.
> Jun 20 17:14:31 iris-gaia-green-20220405-zeppelin
> systemd-logind[1101]: Removed session 109.
> 
> If I'm translating this correctly your session logged out after 1:41
> min, so perhaps that is when the gunzip processed was stopped.
> I think the following was the command you ran:
>      
>      gunzip -r -v * >& nohup_gunzip.out &
> 
> Which would probably be killed after your ssh connection is closed.
> Instead you could try using nohup like this:
> 
>     nohup gunzip -r -v *  > nohup_gunzip.out 2>&1 &
> 
> This should run it in the background, and it would continue running
> even if you close your connection.

**Comment by NigelHambly** [comment]
Yeah my bad - I meant to include the nohup incantation but didn't, and it consequently died when I logged out.

Sorry for the noise.
