### ISSUE TITLE
Openstack upgrades causing issues with current deploy

### ISSUE THREAD

**Issue by stvoutsin** [wfau/aglais#804]
On 28/06/2022 while nch was running some Spark jobs, we noticed the following issues which may be related to an email about some Openstack upgrades that were due to be performed. Some of the symptoms:

- Permission denied errors, when trying to access (cd) to any of the /user directories
- Permission denied errors, when trying to access (cd) some of the /data directories. (any in twomass fail, gaia/gdr2 works)
- Unresponsive Zeppelin (HTTP access to public URL) (we were running 3 separate deploys, all seem to become unresponsive at the same time)

**Comment by NigelHambly** [comment]
Here's what I see from the linux command line:

% ssh -L '8088:master01:8088' fedora@128.232.227.196
Last login: Tue Jun 28 12:17:57 2022 from 192.108.120.86
[fedora@iris-gaia-blue-20220627-zeppelin ~]$ cd /user/nch
-bash: cd: /user/nch: Permission denied
[fedora@iris-gaia-blue-20220627-zeppelin ~]$ 
[fedora@iris-gaia-blue-20220627-zeppelin ~]$ cd /user/nch
-bash: cd: /user/nch: Permission denied
[fedora@iris-gaia-blue-20220627-zeppelin ~]$ whoami
fedora
[fedora@iris-gaia-blue-20220627-zeppelin ~]$ whoami
fedora
[fedora@iris-gaia-blue-20220627-zeppelin ~]$ pwd
/home/fedora
[fedora@iris-gaia-blue-20220627-zeppelin ~]$ ls
spark-warehouse  zeppelin  zeppelin-0.10.0-bin-all
[fedora@iris-gaia-blue-20220627-zeppelin ~]$ ls /home/nch
ls: cannot open directory '/home/nch': Permission denied

**Comment by NigelHambly** [comment]
All seemed to coincide with Zeppeling UI, Spark admin UI and Grafana UI all freezing. My understanding is that Arcus OpenStack cloud maintenance has been on-going today.

**Comment by stvoutsin** [comment]
Looking through the Grafana UI, we notice 4 separate gaps with a few minutes without any feedback/reporting

**Comment by Zarquan** [comment]
All this coincides with planned maintenance at Cambridge:
> 1. Tuesday 28th June - OpenStack maintenance
> --------------------
> The OpenStack part of the maintenance originally scheduled for 21st had to be delayed, so on 28th June the OpenStack controller nodes will be receiving operating system upgrades throughout the day. This is not expected to cause disruption, but if the unexpected occurs it could theoretically disturb network access (since the networking for the newer parts of CSD3 is managed by OpenStack).

**Comment by Zarquan** [comment]
Slack discussion with Pau and John at Cambridge :

**Comment by Zarquan** [comment]
A test deployment built around 16:00 was fine, all the CephFS shares were accessible and had the right data.

**Comment by stvoutsin** [comment]
Noticed two glitches in the Grafana monitoring again around 11:40am today (2022-06-29). During this time Nigel had started an DR3 ingest job, which failed with the same error message:

`Job aborted due to stage failure: Task 5641 in stage 14.0 failed 4 times, most recent failure: Lost task 5641.3 in stage 14.0 (TID 17817) (worker03 executor 215): java.io.FileNotFoundException: File file:/user/nch/CSV/GDR3/cdn.gea.esac.esa.int/Gaia/gdr3/Spectroscopy/xp_continuous_mean_spectrum/XpContinuousMeanSpectrum_127786-129587.csv does not exi`

**Comment by NigelHambly** [comment]
yeah the ingest job has failed - can we buzz arcus/openstack ops to see if they're still fiddling?

**Comment by Zarquan** [comment]
I saw network errors in a build I was running at around 12:00 this afternoon.
Contacting Cambridge to see what is happening.

**Comment by Zarquan** [comment]
Also getting timeout errors in Ansible when creating new VMs.
```
TASK [Create our Zeppelin node] ************************************************
fatal: [localhost]: FAILED! => {"changed": false, "extra_data": {"data": null, "details": "None", "response": "None"}, "msg": "Timeout waiting for the server to come up."}
```

**Comment by NigelHambly** [comment]
Thanks - I guess we should hold off relaunching the ingest?

**Comment by Zarquan** [comment]
Yep, they are looking into it now. I'll send an email when we have a result.

**Comment by Zarquan** [comment]
Errors when deleting resources from test build on `iris-gaia-red`
````
---- ----
Deleting volumes
- Deleting volume [97db0e50-d44f-44e7-bee3-aa5cfbe19a20]
Failed to delete volume with name or ID '97db0e50-d44f-44e7-bee3-aa5cfbe19a20': Invalid volume: Volume status must be available or error or error_restoring or error_extending or error_managing and must not be migrating, attached, belong to a group, have snapshots or be disassociated from snapshots after volume transfer. (HTTP 400) (Request-ID: req-ac401d71-fcec-4de1-96f4-9581aa2116c9)
1 of 1 volumes failed to delete.
- Deleting volume [a586d324-f556-4b57-87fe-9a025a230507]
Failed to delete volume with name or ID 'a586d324-f556-4b57-87fe-9a025a230507': Invalid volume: Volume status must be available or error or error_restoring or error_extending or error_managing and must not be migrating, attached, belong to a group, have snapshots or be disassociated from snapshots after volume transfer. (HTTP 400) (Request-ID: req-5045b964-38de-40d1-b0b2-ac3d9d704ff5)
1 of 1 volumes failed to delete.
- Deleting volume [66aacdb6-7757-4014-a32b-d5295dd5d41a]
Failed to delete volume with name or ID '66aacdb6-7757-4014-a32b-d5295dd5d41a': Invalid volume: Volume status must be available or error or error_restoring or error_extending or error_managing and must not be migrating, attached, belong to a group, have snapshots or be disassociated from snapshots after volume transfer. (HTTP 400) (Request-ID: req-07ba75e5-fc32-407c-a075-bc960dd0bbab)
1 of 1 volumes failed to delete.
- Deleting volume [d15cd32f-0a4c-4142-b447-5517caf9974c]
Failed to delete volume with name or ID 'd15cd32f-0a4c-4142-b447-5517caf9974c': Invalid volume: Volume status must be available or error or error_restoring or error_extending or error_managing and must not be migrating, attached, belong to a group, have snapshots or be disassociated from snapshots after volume transfer. (HTTP 400) (Request-ID: req-aaf38d8e-4936-48cc-98a7-5702a9faa3c1)
1 of 1 volumes failed to delete.
````

**Comment by Zarquan** [comment]
The whole Arcus system is unresponsive.
* Unable to login via the Horizon  GUI
* REST webservice calls hang

We broke the cloud :disappointed:

**Comment by Zarquan** [comment]
Internally, CephFS file shares are still working
````
md5sum /user/nch/CSV/GDR3/cdn.gea.esac.esa.int/Gaia/gdr3/Spectroscopy/xp_continuous_mean_spectrum/XpContinuousMeanSpectrum_127786-129587.csv

    0f9d34e965c769a7ca83a03c0929fb49
````

cloud : iris-gaia-red

**Comment by Zarquan** [comment]
Existing ssh connections still working, unable to connect new ssh connections. 
cloud : iris-gaia-red

**Comment by Zarquan** [comment]
Created a separate issue for the 'stuck' Cinder volumes, #808

**Comment by Zarquan** [comment]
The logged issues have been addressed, but the maintenance work is ongoing.

Quote from Cambridge at 21:40:
> We do still have one controller node to rebuild; the process of taking cloud controllers out of the RabbitMQ message bus cluster hasn't been as smooth as in the staging cluster testing, which was something I had raised earlier as a potential problem to watch for.
> We'll try a different approach for the third and final controller node tomorrow, but be aware that the maintenance isn't done until we send word that it is.

**Comment by NigelHambly** [comment]
Any news?!

In the meantime you may be interested in this: https://arxiv.org/abs/2206.14392

**Comment by Zarquan** [comment]
No news :disappointed: 
I've asked if there is a status page we could check to get updates on how the maintenance work is going but no reply yet.

**Comment by Zarquan** [comment]
> In the meantime you may be interested in this: https://arxiv.org/abs/2206.14392
> _"The presented platform is built on Amazon Web Services (over Kubernetes and S3 abstraction layers)"_

Yep, I was interested in building something like this.
Not sure I want to read about someone else getting there first.

**Comment by Zarquan** [comment]
I've rebooted all the nodes and I'm running checks on the services ...

**Comment by Zarquan** [comment]
All the nodes have been re-booted, services started and tests passed. 
https://github.com/Zarquan/aglais/blob/20220624-zrq-red-deploy/notes/zrq/20220630-02-blue-reboot.txt

Will leave this issue open until Nigel confirms a successful data transfer completed.

**Comment by NigelHambly** [comment]
Seems to be working fine now; just one glitch over night during a 13hr job: single stage failure with detail

org.apache.spark.shuffle.FetchFailedException: Connection from worker09/10.10.1.151:7337 closed

but it seems a re-queue resulted in overall success. Are such things normal and routinely handled as part of Spark's fault-tolerance?

**Comment by Zarquan** [comment]
The networking issues have been resolved.
