### ISSUE TITLE
DR3 data sets for inclusion in automated deploy

### ISSUE THREAD

**Issue by NigelHambly** [wfau/aglais#821]
At this stage the new data sets that should be included in automated deploy from Gaia DR3 (2048 partitioned versions) are 

GDR3_ASTROPHYSICAL_PARAMETERS       
GDR3_EPOCH_PHOTOMETRY  
GDR3_RVS_MEAN_SPECTRUM            
GDR3_XP_SAMPLED_MEAN_SPECTRUM
GDR3_ASTROPHYSICAL_PARAMETERS_SUPP  
GDR3_GAIA_SOURCE       
GDR3_XP_CONTINUOUS_MEAN_SPECTRUM  
GDR3_XP_SUMMARY

as available at /user/nch/PARQUET/GDR3. Copies/links should be made as appropriate.

At some point in the future there will be more, but for now this is what we have, and what is assumed to be available in gaiadmpsetup.

**Comment by stvoutsin** [comment]
I've setup copy of the remaining data sets on green to allow Nigel to continue development of the gaiadmpsetup library. This was done using the following command:

```
pushd /data/gaia/GDR3
    sudo ln -s /user/nch/PARQUET/GDR3/GDR3_ASTROPHYSICAL_PARAMETERS                     GDR3_ASTROPHYSICAL_PARAMETERS
    sudo ln -s /user/nch/PARQUET/GDR3/GDR3_EPOCH_PHOTOMETRY                     GDR3_EPOCH_PHOTOMETRY
    sudo ln -s /user/nch/PARQUET/GDR3/GDR3_RVS_MEAN_SPECTRUM                     GDR3_RVS_MEAN_SPECTRUM
    sudo ln -s /user/nch/PARQUET/GDR3/GDR3_XP_SAMPLED_MEAN_SPECTRUM                     GDR3_XP_SAMPLED_MEAN_SPECTRUM
    sudo ln -s /user/nch/PARQUET/GDR3/GDR3_ASTROPHYSICAL_PARAMETERS_SUPP                     GDR3_ASTROPHYSICAL_PARAMETERS_SUPP
    sudo ln -s /user/nch/PARQUET/GDR3/GDR3_XP_CONTINUOUS_MEAN_SPECTRUM                     GDR3_XP_CONTINUOUS_MEAN_SPECTRUM
    sudo ln -s /user/nch/PARQUET/GDR3/GDR3_XP_SUMMARY                     GDR3_XP_SUMMARY
popd
```

@NigelHambly could you test the notebooks on Green with the new links to see if they work ok? 
TODO: We obviously still need to include them in the automated deploy scripts

**Comment by Zarquan** [comment]
Added a task to create a Ceph share for the new data #823

**Comment by Zarquan** [comment]
What happened to GDR3_EPOCH_PHOTOMETRY ?
It isn't in `/user/nch/PARQUET/GDR3` so it didn't transferred to the DR3 CephFS share.
