### ISSUE TITLE
pip install GaiaXPy

### ISSUE THREAD

**Issue by NigelHambly** [wfau/aglais#825]
The GaiaXPy library is now available, world public release, via pip install - see https://gaiaxpy.readthedocs.io/en/latest/installation.html

This trumps all ad-hoc snapshots taken, and version control shenanigans, previously. 

Please incorporate into the standard automated deploy.

**Comment by Zarquan** [comment]
We should also delete the Ceph share allocated for our copy of the gaiaxpy code from svn.

**Comment by Zarquan** [comment]
Found an issue in our example notebook.
* https://github.com/wfau/aglais/issues/914#issuecomment-1193898689
* https://github.com/wfau/aglais/issues/914#issuecomment-1193939653

We need to update the example notebook with this fix.
