### ISSUE TITLE
Update Gaiadmpsetup testing notebook (Aglais-testing)

### ISSUE THREAD

**Issue by stvoutsin** [wfau/aglais#826]
Missmatch between the expected tables produced causes the gaiadmpsetup testing notebook to fail

**Actual tables:**
['astrophysical_parameters', 'astrophysical_parameters_supp', 'gaia_source', 'rvs_mean_spectrum', 'xp_continuous_mean_spectrum', 'xp_sampled_mean_spectrum', 'xp_summary']

**Expected tables:**
['gaia_source', 'gaia_source_allwise_best_neighbours', 'gaia_source_ps1_best_neighbours', 'gaia_source_tmasspsc_best_neighbours']

@NigelHambly Can you confirm if the actual tables are the ones we should expect when importing gaiadmpsetup? Are the neighbour tables no longer created?

**Comment by NigelHambly** [comment]
Oops this is my bad. The check doesn't switch into the relevant context to check for the tables: it needs to be in gaiaedr3 to when looking for the XM tables for example. I'll fix and create a PR.

**Comment by NigelHambly** [comment]
BTW your gaiadmpsetup testing notebook would need to specify DB context as well as table lists now as we have two distinct namespaces gaiaedr3 and gaiadr3 (needed of course to distinguish between gaia_source which is present in both).
