### ISSUE TITLE
User manual for Spark admin GUI

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#86]
GitHub md files, with embedded screen shots demonstrating key parts of the GUI
- How to check if a task is running on the head or distributed to the Spark workers
- ....

**Comment by stvoutsin** [comment]
Alot of useful information on the Spark GUI is here: https://spark.apache.org/docs/3.0.0-preview/web-ui.html. I've beem experimenting with running different Spark jobs and observing the GUI, and it is quite helpful for understanding the flow of the job and the data

**Comment by stvoutsin** [comment]
I've started compiling some screenshots and notes, but as there is a lot of information to cover and understand,  this may have to be a longer term task.

**Comment by Zarquan** [comment]
> there is a lot of information to cover and understand

Yep - which is why we need to share what we find out so we don't spend time repeating things.

**Comment by Zarquan** [comment]
> I've beem experimenting with running different Spark jobs and observing the GUI, and it is quite helpful for understanding the flow of the job and the data

This is good stuff. This exactly the kind of information we need to share so we can understand how it all works together.

**Comment by stvoutsin** [comment]
Do we need this if we are not going to be exposing the Spark UI to external users? Also there are existing manuals for this which are probably better than what I could come up with like :

https://spark.apache.org/docs/3.0.0-preview/web-ui.html
https://docs.cloudera.com/documentation/enterprise/5-9-x/topics/operation_spark_applications.html

My suggestion is that we either close this issue, or label it as a stretch goal, unless there is a good reason not to.

**Comment by Zarquan** [comment]
The notes would be for us rather than the end users.

- If we use the REST webservice API to manage and monitor Spark we can document how to use it using text notes checked in to git.
- If we use the GUI to manage and monitor Spark we still need to share equivalent documentation on how to use it.

Using the GUI doesn't mean we don't make notes.

**Comment by Zarquan** [comment]
> Do we need this if we are not going to be exposing the Spark UI to external users? 
Probably not, so closing this.
