### ISSUE TITLE
stv-hdbscan-2 Python warning

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#89]
Is this a curated notebook ?
Is the Python version warning something we need to be aware of ?

    DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.

**Comment by stvoutsin** [comment]
This is a copy of the the Kounkel and Covey groups demo, with some small modifications to the code to get it working with a small dataset. The Python version warning looks like something we need to fix. I'll create a task to move version from Python 2.7 to Python 3.

**Comment by stvoutsin** [comment]
To answer your question, probably not a curated one, just a notebook experiment.

**Comment by Zarquan** [comment]
> To answer your question, probably not a curated one, just a notebook experiment.

Can we move things into a couple of top level folders `/experiments` and `/examples` ?

**Comment by Zarquan** [comment]
If #91 is tracking the Python version issue, then this can close ?

**Comment by stvoutsin** [comment]
Yep #91 should cover this.
