### ISSUE TITLE
Change version of Python in Spark & Zeppelin nodes from 2.7 to 3.0

### ISSUE THREAD

**Issue by stvoutsin** [wfau/aglais#91]
Notebooks on current setup are getting Deprecation warnings:

> DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.

We need to change from using Python 2.7 to Python3+.
Do we change to Python3, Python3.4 or Python 3.6? 
Do we want to update the existing prototype system, or just the configurations for newer deployments?

**Comment by Zarquan** [comment]
Good question - we need to check we remain compatible with all the libraries that our users are going to install. This feeds into the testing infrastructure tasks.
We need to be able to update the Python version to a new version, deploy a test system and run a set of integration tests to check it doesn't cause problems.

**Comment by Zarquan** [comment]
The Ansible deploy installs Python3, but it doesn't set a specific minor version.
https://github.com/wfau/aglais/blob/649beebb83b548950e208e9dcd1ec6f777c4569d/experiments/zrq/ansible/23-install-python.yml

Changing it to deploy a specific version would be easy enough.

**Comment by Zarquan** [comment]
What version of Python does the k8s deploy install ?

**Comment by Zarquan** [comment]
The standard Hadoop distribution from Apache doesn't cope well with the latest versions of Java, so I had to explicitly set the Java version.

**Comment by Zarquan** [comment]
This is now configured as part of the PySpark interpreter and worker images (#158).

**Comment by Zarquan** [comment]
I think this is done now.
