### ISSUE TITLE
Change default hostname to use Zeppelin IP address

### ISSUE THREAD

**Issue by stvoutsin** [wfau/aglais#925]
We need to change the default value that we pass in as a hostname in the create-all script here:
https://github.com/wfau/aglais/blob/master/deployments/hadoop-yarn/bin/create-all.sh#L49
Currently we pass in a hardcoded URL (zeppelin.gaia-dmp.uk), but this will not work if that domain name is not pointed to the IP address of that Zeppelin instance.
Instead we should probably use the IP address of Zeppelin itself, and that way the NGINX proxy is setup and works correctly using the IP address of the Zeppelin node and port 80.
(This has been tested)

**Comment by Zarquan** [comment]
We don't need to use IP addresses, we have red green and blue entries in DuckDNS.
See #838
