### ISSUE TITLE
Link for Gaia DR3 XP spectra

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#938]
Examle 5. Working with Gaia XP spectra
Just checking - Is this the right link for '[Gaia DR3 XP spectra online documentation](https://gea.esac.esa.int/archive/documentation/GDR3/Data_processing/chap_cu5pho/cu5pho_sec_specProcessing/cu5pho_ssec_specInternCal.html#SSS3)' ?

**Comment by NigelHambly** [comment]
Yes it is the right link.
